name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            DISCORD_ROLE_MENTION_ID
            DISCORD_WEBHOOK_URL
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          DISCORD_ROLE_MENTION_ID: ${{ secrets.DISCORD_ROLE_MENTION_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
